import { useEffect, useMemo, useRef, useState } from 'react'
import type { DragEvent, ReactNode, RefObject } from 'react'
import { createPortal } from 'react-dom'
import type { Task, TaskCollection } from '../types'
import { CalendarClockIcon, CalendarDaysIcon, CalendarIcon, CheckCheckIcon, CheckIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, CopyIcon, FlagIcon, GripVerticalIcon, InboxIcon, ListPlusIcon, Maximize2Icon, Minimize2Icon, MoreHorizontalIcon, PencilIcon, PlayIcon, PlusIcon, SquareCheckBigIcon, SunIcon, TrashIcon } from './Icons'
import { formatDateTime } from '../dateFormat'

type SystemView = 'today' | 'upcoming' | 'inbox' | 'completed'
type View = SystemView | 'custom'
type Props = { tasks: Task[]; collections: TaskCollection[]; showCompletedTasks: boolean; expanded: boolean; dailyGoalTaskIds: string[]; onChange(tasks: Task[]): void; onCollectionsChange(collections: TaskCollection[]): void; onToggleCompleted(): void; onStartFocus(task: Task): void; onSetDailyGoal(task: Task): void; onExpandedChange(expanded: boolean): void }
type RowsProps = { tasks: Task[]; collections: TaskCollection[]; compact: boolean; editingId: string | null; editingTitle: string; menuId: string | null; subtaskDraftFor: string | null; subtaskDraft: string; dailyGoalTaskIds: string[]; onToggle(id: string): void; onUpdate(id: string, patch: Partial<Task>): void; onMove(task: Task, target: string): void; onDragStart(task: Task, event: DragEvent<HTMLElement>): void; onDragEnd(): void; onMenu(id: string | null): void; onEditStart(task: Task): void; onEditChange(value: string): void; onEditCommit(): void; onEditCancel(): void; onSubtaskStart(id: string): void; onSubtaskCancel(): void; onSubtaskChange(value: string): void; onSubtaskCommit(task: Task): void; onStartFocus(task: Task): void; onSetDailyGoal(task: Task): void; onDuplicate(task: Task): void; onDelete(id: string): void }

const systemViews: Record<SystemView, { label: string; icon: ReactNode }> = {
  today: { label: 'Today', icon: <SunIcon className="size-5" /> }, upcoming: { label: 'Upcoming', icon: <CalendarIcon className="size-5" /> }, inbox: { label: 'Inbox', icon: <InboxIcon className="size-5" /> }, completed: { label: 'Completed', icon: <CheckCheckIcon className="size-5" /> },
}
const startDay = (date = new Date()) => new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime()
const sameToday = (value?: string) => Boolean(value) && startDay(new Date(value!)) === startDay()
const futureDay = (value?: string) => Boolean(value) && startDay(new Date(value!)) > startDay()
const now = () => new Date().toISOString()
const tomorrow = () => { const date = new Date(); date.setDate(date.getDate() + 1); return date.toISOString() }
const nextSunday = () => { const date = new Date(); date.setDate(date.getDate() + ((7 - date.getDay()) % 7 || 7)); return date.toISOString() }
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const monthStart = (value?: string) => { const date = value ? new Date(value) : new Date(); return new Date(date.getFullYear(), date.getMonth(), 1) }

function tasksFor(tasks: Task[], view: View, listId: string | null, showCompleted: boolean) {
  const active = showCompleted || view === 'completed' ? tasks : tasks.filter(task => !task.done)
  if (view === 'today') return active.filter(task => sameToday(task.reminderAt) || (!task.reminderAt && task.listId === 'today'))
  if (view === 'upcoming') return active.filter(task => futureDay(task.reminderAt))
  if (view === 'inbox') return active.filter(task => !task.reminderAt && task.listId !== 'today')
  if (view === 'completed') return tasks.filter(task => task.done)
  return active.filter(task => task.listId === listId)
}

export function TaskList({ tasks, collections, showCompletedTasks, expanded, dailyGoalTaskIds, onChange, onCollectionsChange, onToggleCompleted, onStartFocus, onSetDailyGoal, onExpandedChange }: Props) {
  const [view, setView] = useState<View>('today')
  const [customListId, setCustomListId] = useState<string | null>(null)
  const [draft, setDraft] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editingTitle, setEditingTitle] = useState('')
  const [menuId, setMenuId] = useState<string | null>(null)
  const [subtaskDraftFor, setSubtaskDraftFor] = useState<string | null>(null)
  const [subtaskDraft, setSubtaskDraft] = useState('')
  const [draggedTaskId, setDraggedTaskId] = useState<string | null>(null)
  const [newTaskTarget, setNewTaskTarget] = useState<string>('today')
  const [createListOpen, setCreateListOpen] = useState(false)
  const createListAnchor = useRef<HTMLButtonElement | null>(null)
  const [newListName, setNewListName] = useState('')
  const visible = useMemo(() => tasksFor(tasks, view, customListId, showCompletedTasks), [tasks, view, customListId, showCompletedTasks])
  const currentList = collections.find(item => item.id === customListId)
  const title = view === 'custom' ? currentList?.name ?? 'Inbox' : systemViews[view].label
  const icon = view === 'custom' ? <ListPlusIcon className="size-6" /> : systemViews[view].icon
  const update = (id: string, patch: Partial<Task>) => onChange(tasks.map(task => task.id === id ? { ...task, ...patch } : task))
  const toggle = (id: string) => { const task = tasks.find(item => item.id === id); if (task) update(id, { done: !task.done }) }
  const selectSystem = (next: SystemView) => { setView(next); setCustomListId(null); setNewTaskTarget(next); setEditingId(null); setMenuId(null) }
  const selectCustom = (id: string) => { setView('custom'); setCustomListId(id); setNewTaskTarget(id); setEditingId(null); setMenuId(null) }
  const move = (task: Task, target: string) => { const patch: Partial<Task> = target === 'today' ? { listId: undefined, reminderAt: now(), done: false } : target === 'upcoming' ? { listId: undefined, reminderAt: tomorrow(), done: false } : target === 'inbox' ? { listId: undefined, reminderAt: undefined, done: false } : target === 'completed' ? { done: true } : { listId: target, done: false }; update(task.id, patch); setMenuId(null) }
  const addTask = (target = newTaskTarget) => { const value = draft.trim(); if (!value) return; const defaults: Partial<Task> = target === 'today' ? { reminderAt: now() } : target === 'upcoming' ? { reminderAt: tomorrow() } : target === 'completed' ? { reminderAt: now(), done: true } : target === 'inbox' ? {} : { listId: target }; onChange([...tasks, { id: crypto.randomUUID(), title: value, done: false, source: 'local', ...defaults }]); setDraft('') }
  const createList = () => { const name = newListName.trim(); if (!name) return; const list = { id: crypto.randomUUID(), name }; onCollectionsChange([...collections, list]); setCreateListOpen(false); setNewListName(''); selectCustom(list.id) }
  const renameList = (id: string, name: string) => onCollectionsChange(collections.map(list => list.id === id ? { ...list, name } : list))
  const deleteList = (id: string) => {
    onCollectionsChange(collections.filter(list => list.id !== id))
    onChange(tasks.map(task => task.listId === id ? { ...task, listId: undefined } : task))
    if (customListId === id) selectSystem('inbox')
  }
  const beginEdit = (task: Task) => { setEditingId(task.id); setEditingTitle(task.title); setMenuId(null) }
  const commitEdit = () => { if (editingId && editingTitle.trim()) update(editingId, { title: editingTitle.trim() }); setEditingId(null); setEditingTitle('') }
  const commitSubtask = (task: Task) => { if (subtaskDraft.trim()) update(task.id, { subTasks: [...(task.subTasks ?? []), { id: crypto.randomUUID(), title: subtaskDraft.trim(), done: false }] }); setSubtaskDraftFor(null); setSubtaskDraft('') }
  const startDrag = (task: Task, event: DragEvent<HTMLElement>) => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', task.id); setDraggedTaskId(task.id) }
  const endDrag = () => setDraggedTaskId(null)
  const draggedTask = draggedTaskId ? tasks.find(task => task.id === draggedTaskId) ?? null : null
  const rows = <TaskRows tasks={expanded ? visible : tasksFor(tasks, 'today', null, showCompletedTasks).slice(0, 3)} compact={!expanded} collections={collections} editingId={editingId} editingTitle={editingTitle} menuId={menuId} subtaskDraftFor={subtaskDraftFor} subtaskDraft={subtaskDraft} dailyGoalTaskIds={dailyGoalTaskIds} onToggle={toggle} onUpdate={update} onMove={move} onDragStart={startDrag} onDragEnd={endDrag} onMenu={setMenuId} onEditStart={beginEdit} onEditChange={setEditingTitle} onEditCommit={commitEdit} onEditCancel={() => { setEditingId(null); setEditingTitle('') }} onSubtaskStart={id => { setSubtaskDraftFor(id); setSubtaskDraft('') }} onSubtaskCancel={() => { setSubtaskDraftFor(null); setSubtaskDraft('') }} onSubtaskChange={setSubtaskDraft} onSubtaskCommit={commitSubtask} onStartFocus={onStartFocus} onSetDailyGoal={onSetDailyGoal} onDuplicate={task => onChange([...tasks, { ...task, id: crypto.randomUUID(), title: `${task.title} (copy)`, done: false }])} onDelete={id => onChange(tasks.filter(task => task.id !== id))} />
  if (!expanded) return <section className="luxe-glass-surface luxe-glass-surface--panel luxe-glass-surface--dark-panel relative h-[172px] w-[526px] max-w-[calc(100vw-32px)] overflow-hidden rounded-[10px] bg-[radial-gradient(circle_at_94%_110%,rgba(18,33,40,.7),transparent_45%),radial-gradient(circle_at_18%_0%,rgba(61,45,39,.34),transparent_36%),linear-gradient(135deg,rgba(16,18,20,.98),rgba(18,16,17,.95)_52%,rgba(13,16,20,.98))] px-7 py-6 text-white shadow-[0_28px_80px_rgba(0,0,0,.48)]"><TaskHeader title="Today's tasks" icon={<SunIcon className="size-6" />} expanded={false} view="today" showCompleted={showCompletedTasks} onExpand={() => onExpandedChange(true)} onToggleCompleted={onToggleCompleted} onClearCompleted={() => onChange(tasks.filter(task => !task.done))} /><div className="space-y-2">{rows}</div><div className="mt-4"><TaskInput draft={draft} setDraft={setDraft} add={() => addTask('today')} compact /></div></section>
  return <section className="luxe-glass-surface luxe-glass-surface--panel luxe-glass-surface--dark-panel relative h-[50vh] w-[50vw] max-h-[calc(100vh-32px)] max-w-[calc(100vw-32px)] overflow-hidden rounded-[12px] bg-[radial-gradient(circle_at_88%_96%,rgba(14,29,37,.68),transparent_38%),radial-gradient(circle_at_28%_12%,rgba(70,49,42,.36),transparent_42%),linear-gradient(145deg,rgba(43,31,28,.98),rgba(28,25,25,.98)_38%,rgba(12,17,22,.99))] text-white shadow-[0_28px_80px_rgba(0,0,0,.48)]"><div className="grid h-full grid-cols-[36%_minmax(0,1fr)]"><TaskSidebar tasks={tasks} collections={collections} view={view} customListId={customListId} draggedTask={draggedTask} onSystem={selectSystem} onCustom={selectCustom} onMove={move} onDragEnd={endDrag} onCreate={anchor => { createListAnchor.current = anchor; setCreateListOpen(true) }} onRenameList={renameList} onDeleteList={deleteList} /><section className="flex min-h-0 flex-col"><TaskHeader title={title} icon={icon} expanded view={view} showCompleted={showCompletedTasks} onExpand={() => { selectSystem('today'); onExpandedChange(false) }} onToggleCompleted={onToggleCompleted} onClearCompleted={() => onChange(tasks.filter(task => !task.done))} /><div className="min-h-0 flex-1 overflow-y-auto px-5 pb-4"><button type="button" className="mb-2 h-12 w-full rounded-xl border border-dashed border-white/10 text-center text-xs font-semibold text-white/35 transition hover:border-white/25">Drop here to move to top level</button><div className="space-y-1">{rows}</div></div><TaskInput draft={draft} setDraft={setDraft} add={addTask} compact={false} /></section></div>{createListOpen && <CreateListPopover anchor={createListAnchor.current} open={createListOpen} collections={collections} tasks={tasks} onSelect={id => { selectCustom(id); setCreateListOpen(false) }} name={newListName} onName={setNewListName} onClose={() => { setCreateListOpen(false); setNewListName('') }} onCreate={createList} />}</section>
}

function TaskHeader({ title, icon, expanded, view, showCompleted, onExpand, onToggleCompleted, onClearCompleted }: { title: string; icon: ReactNode; expanded: boolean; view: View; showCompleted: boolean; onExpand(): void; onToggleCompleted(): void; onClearCompleted(): void }) { const [open, setOpen] = useState(false); const anchor = useRef<HTMLButtonElement>(null); return <header className={`relative flex items-center justify-between ${expanded ? 'px-7 py-6' : 'mb-4 gap-4'}`}><button type="button" onClick={() => !expanded && onExpand()} className="flex min-w-0 items-center gap-4 text-left"><span className="shrink-0 text-white/90">{icon}</span><span className={`truncate font-semibold leading-none tracking-[-.025em] ${expanded ? 'text-[calc(22px*var(--task-font-scale,0.88))]' : 'text-[calc(20px*var(--task-font-scale,0.88))]'}`}>{title}</span>{!expanded && <ChevronDownIcon className="size-4 text-white/45" />}</button><div className="flex items-center gap-2"><button ref={anchor} type="button" onClick={() => setOpen(value => !value)} className="flex size-8 items-center justify-center rounded-full text-white/62 hover:bg-white/10" aria-label="Task options"><MoreHorizontalIcon className="size-5" /></button><button type="button" onClick={onExpand} className={`flex items-center justify-center rounded-full text-white/60 hover:bg-white/10 ${expanded ? 'size-9' : 'size-8'}`}>{expanded ? <Minimize2Icon className="size-4" /> : <Maximize2Icon className="size-4" />}</button></div>{open && <ListOptionsMenu anchor={anchor} expanded={expanded} completedView={view === 'completed'} showCompleted={showCompleted} onClose={() => setOpen(false)} onToggleCompleted={onToggleCompleted} onClearCompleted={onClearCompleted} />}</header> }

function ListOptionsMenu({ anchor, expanded, showCompleted, onClose, onToggleCompleted, onClearCompleted }: { anchor: RefObject<HTMLButtonElement | null>; expanded: boolean; completedView: boolean; showCompleted: boolean; onClose(): void; onToggleCompleted(): void; onClearCompleted(): void }) { const [stayOpen, setStayOpen] = useState(false); const [position, setPosition] = useState({ top: 12, left: 12 }); const width = 310; useEffect(() => { const place = () => { const rect = anchor.current?.getBoundingClientRect(); if (!rect) return; setPosition({ top: Math.min(rect.bottom + 10, window.innerHeight - 24), left: Math.max(12, Math.min(rect.right - width, window.innerWidth - width - 12)) }) }; place(); window.addEventListener('resize', place); return () => window.removeEventListener('resize', place) }, [anchor, width]); const action = (run: () => void) => { run(); if (!stayOpen) onClose() }; if (!expanded) return createPortal(<div style={{ position: 'fixed', top: position.top, left: position.left, width }} className="z-[100] rounded-[14px] border border-white/10 bg-[#302d2c]/[.99] p-2 text-[13px] font-medium shadow-[0_18px_42px_rgba(0,0,0,.36)]"><button type="button" onClick={() => action(onToggleCompleted)} className="flex h-10 w-full items-center rounded-xl px-3 hover:bg-white/10">{showCompleted ? 'Hide completed tasks' : 'Show completed tasks'}</button></div>, document.body); return createPortal(<div style={{ position: 'fixed', top: position.top, left: position.left, width: 'min(310px, calc(100vw - 24px))' }} className="z-[100] rounded-[14px] border border-white/15 bg-[#302e2d]/[.99] p-2 text-white shadow-[0_24px_60px_rgba(0,0,0,.45)] backdrop-blur-xl"><button type="button" onClick={() => action(() => undefined)} className="flex h-10 w-full items-center gap-3 rounded-xl bg-white/[.13] px-3 text-left text-[calc(15px*var(--task-font-scale,0.88))] font-semibold hover:bg-white/[.18]"><span className="text-white/60">⟳</span>Show top task in center</button><ListOption icon={<CheckIcon />} label="Clear completed tasks" onClick={() => action(onClearCompleted)} /><ListDivider /><ListOption icon={<span>↕</span>} label="Sort list by" value="Manual" onClick={() => undefined} /><ListOption icon={<ListPlusIcon />} label="Add tasks" value="Bottom" onClick={() => undefined} /><ListOption icon={<span>◉</span>} label="Show completed" value={showCompleted ? 'Always' : 'Today'} onClick={onToggleCompleted} /><ListDivider /><button type="button" onClick={() => setStayOpen(value => !value)} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[calc(15px*var(--task-font-scale,0.88))] font-semibold hover:bg-white/10"><FlagIcon className="size-4 text-white/65" />Stay open <span className={`ml-auto flex h-6 w-11 items-center rounded-full p-1 ${stayOpen ? 'justify-end bg-white/65' : 'justify-start bg-white/25'}`}><span className="size-5 rounded-full bg-white" /></span></button></div>, document.body) }
function ListOption({ icon, label, value, onClick }: { icon: ReactNode; label: string; value?: string; onClick(): void }) { return <button type="button" onClick={onClick} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[calc(15px*var(--task-font-scale,0.88))] font-semibold hover:bg-white/10"><span className="flex size-4 items-center justify-center text-white/65 [&>svg]:size-4">{icon}</span>{label}{value && <span className="ml-auto text-[calc(13px*var(--task-font-scale,0.88))] text-white/40">{value}</span>}</button> }
function ListDivider() { return <div className="my-1 h-px bg-white/15" /> }

function TaskSidebar({ tasks, collections, view, customListId, draggedTask, onSystem, onCustom, onMove, onDragEnd, onCreate, onRenameList, onDeleteList }: { tasks: Task[]; collections: TaskCollection[]; view: View; customListId: string | null; draggedTask: Task | null; onSystem(view: SystemView): void; onCustom(id: string): void; onMove(task: Task, target: string): void; onDragEnd(): void; onCreate(anchor: HTMLButtonElement): void; onRenameList(id: string, name: string): void; onDeleteList(id: string): void }) {
  const drop = (target: string) => (event: DragEvent<HTMLElement>) => { event.preventDefault(); if (draggedTask) onMove(draggedTask, target); onDragEnd() }
  const allow = (event: DragEvent<HTMLElement>) => { if (draggedTask) event.preventDefault() }
  return <aside className="flex min-h-0 flex-col border-r border-white/10 px-6 py-6"><div className="mb-8 flex items-center gap-3"><SquareCheckBigIcon className="size-5 text-white/90" /><span className="text-[calc(22px*var(--task-font-scale,0.88))] font-semibold leading-none tracking-[-.025em]">Tasks</span><ChevronDownIcon className="size-4 text-white/45" /></div><nav className="space-y-2">{(Object.keys(systemViews) as SystemView[]).map(id => <button key={id} type="button" onClick={() => onSystem(id)} onDragOver={allow} onDrop={drop(id)} style={{ fontSize: 'calc(16px * var(--task-font-scale, 0.88))' }} className={`flex h-12 w-full items-center gap-3 rounded-xl px-3 text-left font-semibold transition ${view === id ? 'bg-white/13 text-white shadow-[inset_0_1px_0_rgba(255,255,255,.08)]' : 'text-white/88 hover:bg-white/8'}`}><span className="flex size-5 shrink-0 items-center justify-center text-white/66">{systemViews[id].icon}</span><span className="min-w-0 flex-1 truncate">{systemViews[id].label}</span><span className="tabular-nums text-white/42">{tasksFor(tasks, id, null, id === 'completed').length}</span></button>)}{collections.map(list => <CustomListRow key={list.id} list={list} count={tasks.filter(task => task.listId === list.id && !task.done).length} active={view === 'custom' && customListId === list.id} onSelect={() => onCustom(list.id)} onDragOver={allow} onDrop={drop(list.id)} onRename={name => onRenameList(list.id, name)} onDelete={() => onDeleteList(list.id)} />)}<button type="button" onClick={event => onCreate(event.currentTarget)} style={{ fontSize: 'calc(16px * var(--task-font-scale, 0.88))' }} className="mt-4 flex h-12 w-full items-center rounded-xl px-3 text-left text-[calc(16px*var(--task-font-scale,0.88))] font-semibold text-white/88 hover:bg-white/8">New List</button></nav></aside>
}

function CustomListRow({ list, count, active, onSelect, onDragOver, onDrop, onRename, onDelete }: { list: TaskCollection; count: number; active: boolean; onSelect(): void; onDragOver(event: DragEvent<HTMLElement>): void; onDrop(event: DragEvent<HTMLElement>): void; onRename(name: string): void; onDelete(): void }) {
  const anchor = useRef<HTMLButtonElement>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const [editing, setEditing] = useState(false)
  const [name, setName] = useState(list.name)
  const cancelEditRef = useRef(false)
  useEffect(() => setName(list.name), [list.name])
  const commit = () => { if (cancelEditRef.current) { cancelEditRef.current = false; return }; const value = name.trim(); if (value) onRename(value); else setName(list.name); setEditing(false) }
  return <div onDragOver={onDragOver} onDrop={onDrop} className={`group/list relative flex h-11 items-center rounded-xl px-2 transition ${active ? 'bg-white/13 text-white/90' : 'text-white/85 hover:bg-white/8'}`}>
    <span className="mr-2 flex size-5 shrink-0 items-center justify-center text-white/55"><ListPlusIcon className="size-4" /></span>
    {editing ? <input autoFocus value={name} onChange={event => setName(event.target.value)} onBlur={commit} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); if (event.key === 'Escape') { cancelEditRef.current = true; setName(list.name); setEditing(false) } }} aria-label="Rename task list" className="min-w-0 flex-1 bg-transparent text-[calc(15px*var(--task-font-scale,0.88))] font-semibold outline-none" /> : <button type="button" onClick={onSelect} className="min-w-0 flex-1 truncate py-2 text-left text-[calc(15px*var(--task-font-scale,0.88))] font-semibold">{list.name}</button>}
    <span className="px-2 text-[calc(15px*var(--task-font-scale,0.88))] tabular-nums text-white/42">{count}</span>
    <button ref={anchor} type="button" aria-label={`Actions for ${list.name}`} onClick={event => { event.stopPropagation(); setMenuOpen(value => !value) }} className={`flex size-8 shrink-0 items-center justify-center rounded-full text-white/70 transition hover:bg-white/10 ${menuOpen ? 'bg-white/10 opacity-100' : 'pointer-events-none opacity-0 group-hover/list:pointer-events-auto group-hover/list:opacity-100 focus-visible:pointer-events-auto focus-visible:opacity-100'}`}><MoreHorizontalIcon className="size-5" /></button>
    {menuOpen && <CustomListMenu anchor={anchor} onEdit={() => { setMenuOpen(false); cancelEditRef.current = false; setEditing(true) }} onDelete={() => { setMenuOpen(false); onDelete() }} onClose={() => setMenuOpen(false)} />}
  </div>
}

function CustomListMenu({ anchor, onEdit, onDelete, onClose }: { anchor: RefObject<HTMLButtonElement | null>; onEdit(): void; onDelete(): void; onClose(): void }) {
  const menuRef = useRef<HTMLDivElement>(null)
  const [position, setPosition] = useState({ top: 12, left: 12 })
  useEffect(() => {
    const place = () => { const rect = anchor.current?.getBoundingClientRect(); if (rect) setPosition({ top: Math.max(12, Math.min(rect.top - 4, window.innerHeight - 104)), left: Math.max(12, Math.min(rect.right + 8, window.innerWidth - 188)) }) }
    const outside = (event: PointerEvent) => { if (!menuRef.current?.contains(event.target as Node) && !anchor.current?.contains(event.target as Node)) onClose() }
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }
    place(); window.addEventListener('resize', place); document.addEventListener('pointerdown', outside); document.addEventListener('keydown', escape)
    return () => { window.removeEventListener('resize', place); document.removeEventListener('pointerdown', outside); document.removeEventListener('keydown', escape) }
  }, [anchor, onClose])
  return createPortal(<div ref={menuRef} style={{ position: 'fixed', top: position.top, left: position.left, width: 'min(176px, calc(100vw - 24px))' }} className="z-[150] rounded-2xl border border-white/10 bg-[#302d2c]/[.99] p-2 text-white shadow-[0_18px_42px_rgba(0,0,0,.38)] backdrop-blur-xl"><button type="button" onClick={onEdit} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold hover:bg-white/10"><PencilIcon className="size-4 text-white/60" />Edit list</button><button type="button" onClick={onDelete} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold text-red-100 hover:bg-red-500/15"><TrashIcon className="size-4 text-red-200/70" />Delete list</button></div>, document.body)
}
function TaskRows(props: RowsProps) { if (!props.tasks.length) return <p className={props.compact ? 'py-1 text-[calc(15px*var(--task-font-scale,0.88))] font-semibold text-white/38' : 'py-7 text-[calc(15px*var(--task-font-scale,0.88))] font-semibold text-white/38'}>No tasks yet.</p>; return <>{props.tasks.map(task => props.compact ? <CompactTask key={task.id} task={task} {...props} /> : <ExpandedTask key={task.id} task={task} {...props} />)}</> }
function CheckBox({ task, large = false, onToggle }: { task: Task; large?: boolean; onToggle(id: string): void }) { return <button type="button" role="checkbox" aria-checked={task.done} onClick={event => { event.stopPropagation(); onToggle(task.id) }} className={`flex shrink-0 items-center justify-center rounded-full border transition ${large ? 'size-[26px]' : 'size-[22px]'} ${task.done ? 'border-white/35 bg-white/90 text-slate-950' : 'border-white/35 bg-white/[.03] text-transparent hover:border-white/60'}`}>{task.done && <CheckIcon className={large ? 'size-4' : 'size-3.5'} />}</button> }
function CompactTask({ task, ...props }: RowsProps & { task: Task }) { return <div className="flex items-center gap-3 py-1"><CheckBox task={task} onToggle={props.onToggle} />{props.editingId === task.id ? <input autoFocus value={props.editingTitle} onChange={event => props.onEditChange(event.target.value)} onBlur={props.onEditCommit} onKeyDown={event => { if (event.key === 'Enter') props.onEditCommit(); if (event.key === 'Escape') props.onEditCancel() }} className="min-w-0 flex-1 border-b border-white/35 bg-transparent text-[calc(17px*var(--task-font-scale,0.88))] font-semibold leading-6 outline-none" aria-label="Edit task title" /> : <button type="button" onDoubleClick={() => props.onEditStart(task)} className={`min-w-0 flex-1 truncate text-left text-[calc(17px*var(--task-font-scale,0.88))] font-semibold leading-6 ${task.done ? 'text-white/45 line-through' : ''}`}>{task.title}</button>}{task.reminderAt && <span className="text-xs font-semibold text-white/55">{formatDateTime(task.reminderAt)}</span>}<TaskMenuButton task={task} {...props} /></div> }
function ExpandedTask({ task, ...props }: RowsProps & { task: Task }) {
  const cancelSubtaskBlurRef = useRef(false)
  const subtasks = task.subTasks ?? []
  const showSubtasks = subtasks.length > 0 || props.subtaskDraftFor === task.id
  const toggleSubtask = (id: string) => props.onUpdate(task.id, { subTasks: subtasks.map(subtask => subtask.id === id ? { ...subtask, done: !subtask.done } : subtask) })
  return <div className="group/task rounded-2xl border border-transparent px-4 py-2 transition hover:border-white/12 hover:bg-white/[.035]"><div className="relative flex min-w-0 items-center gap-3"><CheckBox task={task} large onToggle={props.onToggle} /><TaskMoveHandle task={task} collections={props.collections} onMove={props.onMove} onDragStart={props.onDragStart} onDragEnd={props.onDragEnd} />{props.editingId === task.id ? <input autoFocus value={props.editingTitle} onChange={event => props.onEditChange(event.target.value)} onBlur={props.onEditCommit} onKeyDown={event => { if (event.key === 'Enter') props.onEditCommit(); if (event.key === 'Escape') props.onEditCancel() }} className="min-w-0 flex-1 border-b border-white/35 bg-transparent py-1 text-[calc(17px*var(--task-font-scale,0.88))] font-semibold outline-none" aria-label="Edit task title" /> : <button type="button" onDoubleClick={() => props.onEditStart(task)} className={`min-w-0 flex-1 truncate text-left text-[calc(17px*var(--task-font-scale,0.88))] font-semibold ${task.done ? 'text-white/45 line-through' : ''}`}>{task.title}</button>}<TaskHoverActions task={task} {...props} /></div>
    {showSubtasks && <div className="mt-2 space-y-1 pl-[50px]">
      {subtasks.map(subtask => <div key={subtask.id} className="flex min-h-9 items-center gap-3"><button type="button" role="checkbox" aria-checked={subtask.done} aria-label={`${subtask.done ? 'Reopen' : 'Complete'} subtask ${subtask.title}`} onClick={() => toggleSubtask(subtask.id)} className={`flex size-[22px] shrink-0 items-center justify-center rounded-full border ${subtask.done ? 'border-white/40 bg-white/85 text-slate-900' : 'border-white/30 text-transparent hover:border-white/55'}`}>{subtask.done && <CheckIcon className="size-3.5" />}</button><span className={`min-w-0 flex-1 truncate text-[calc(16px*var(--task-font-scale,0.88))] font-medium ${subtask.done ? 'text-white/40 line-through' : 'text-white/85'}`}>{subtask.title}</span></div>)}
      {props.subtaskDraftFor === task.id ? <div className="flex min-h-9 items-center gap-3"><PlusIcon className="size-[22px] shrink-0 text-white/40" /><input autoFocus value={props.subtaskDraft} onChange={event => props.onSubtaskChange(event.target.value)} onBlur={event => { if (cancelSubtaskBlurRef.current) { cancelSubtaskBlurRef.current = false; return }; if (!event.currentTarget.parentElement?.contains(event.relatedTarget as Node | null)) props.onSubtaskCommit(task) }} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); if (event.key === 'Escape') { cancelSubtaskBlurRef.current = true; props.onSubtaskCancel() } }} placeholder="New subtask" className="min-w-0 flex-1 bg-transparent text-[calc(16px*var(--task-font-scale,0.88))] font-semibold outline-none placeholder:text-white/38" />
      </div> : <button type="button" onClick={() => props.onSubtaskStart(task.id)} className="flex min-h-9 items-center gap-3 text-[calc(16px*var(--task-font-scale,0.88))] font-semibold text-white/42 transition hover:text-white/75"><PlusIcon className="size-[22px] shrink-0" />New subtask</button>}
      {subtasks.length > 0 && <div className="flex items-center gap-3 pt-1"><DatePickerButton label="Set task date" value={task.reminderAt} onDate={reminderAt => props.onUpdate(task.id, { reminderAt })}><CalendarIcon className="size-5" /></DatePickerButton><TaskMoveHandle task={task} collections={props.collections} onMove={props.onMove} onDragStart={props.onDragStart} onDragEnd={props.onDragEnd} icon={<ListPlusIcon className="size-5" />} size="size-8" draggable={false} /></div>}
    </div>}
  </div>
}function TaskHoverActions({ task, ...props }: RowsProps & { task: Task }) { const fullProps = { ...props, compact: false }; return <div className={`absolute right-0 top-1/2 flex -translate-y-1/2 items-center gap-1 rounded-full bg-[#151719]/95 px-1 transition-opacity ${props.menuId === task.id ? 'pointer-events-auto opacity-100' : 'pointer-events-none opacity-0 group-hover/task:pointer-events-auto group-hover/task:opacity-100'}`}><span className="rounded-full bg-black/20 px-3 py-1 text-xs font-semibold text-white/45">{task.reminderAt ? formatDateTime(task.reminderAt) : 'No date'}</span><QuickDateButton label="Today" onClick={() => props.onUpdate(task.id, { reminderAt: now() })}><SunIcon className="size-4" /></QuickDateButton><DatePickerButton label="Choose date" value={task.reminderAt} onDate={reminderAt => props.onUpdate(task.id, { reminderAt })}><CalendarIcon className="size-4" /></DatePickerButton><button type="button" aria-label="Add subtask" onClick={() => props.onSubtaskStart(task.id)} className="flex size-8 items-center justify-center rounded-full text-white/60 hover:bg-white/10"><ListPlusIcon className="size-4" /></button><TaskMenuButton task={task} {...fullProps} /></div> }
function DatePickerButton({ label, value, children, onDate }: { label: string; value?: string; children: ReactNode; onDate(value?: string): void }) {
  const anchor = useRef<HTMLButtonElement>(null)
  const [open, setOpen] = useState(false)
  const [position, setPosition] = useState({ top: 12, left: 12, maxHeight: 600 })
  const [month, setMonth] = useState(() => monthStart(value))
  const picker = useRef<HTMLDivElement>(null)
  useEffect(() => { if (open) setMonth(monthStart(value)) }, [open, value])
  useEffect(() => {
    if (!open) return
    const place = () => {
      const rect = anchor.current?.getBoundingClientRect()
      if (!rect) return
      const estimatedHeight = 520
      const top = rect.bottom + estimatedHeight + 8 <= window.innerHeight - 12 ? rect.bottom + 8 : Math.max(12, rect.top - estimatedHeight - 8)
      setPosition({ top, left: Math.max(12, Math.min(rect.right - 312, window.innerWidth - 324)), maxHeight: window.innerHeight - 24 })
    }
    const outside = (event: PointerEvent) => { if (!picker.current?.contains(event.target as Node) && !anchor.current?.contains(event.target as Node)) setOpen(false) }
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }
    place()
    window.addEventListener('resize', place)
    document.addEventListener('pointerdown', outside)
    document.addEventListener('keydown', escape)
    return () => { window.removeEventListener('resize', place); document.removeEventListener('pointerdown', outside); document.removeEventListener('keydown', escape) }
  }, [open])
  const today = dateKey(new Date())
  const selected = value ? dateKey(new Date(value)) : ''
  const weekdays = Array.from({ length: 7 }, (_, index) => new Intl.DateTimeFormat(undefined, { weekday: 'short' }).format(new Date(2026, 5, 7 + index)))
  const days = Array.from({ length: 42 }, (_, index) => { const first = new Date(month.getFullYear(), month.getMonth(), 1); first.setDate(first.getDate() - first.getDay() + index); return first })
  const choose = (date?: string) => { onDate(date); setOpen(false) }
  const setDay = (day: Date) => { const date = new Date(day.getFullYear(), day.getMonth(), day.getDate(), 12); choose(date.toISOString()) }
  const shiftMonth = (amount: number) => setMonth(current => new Date(current.getFullYear(), current.getMonth() + amount, 1))
  return <><button ref={anchor} type="button" aria-label={label} onClick={event => { event.stopPropagation(); setOpen(value => !value) }} className="flex size-8 items-center justify-center rounded-lg text-white/55 transition hover:bg-white/10 hover:text-white">{children}</button>{open && createPortal(<div ref={picker} style={{ position: 'fixed', top: position.top, left: position.left, width: 'min(312px, calc(100vw - 24px))', maxHeight: position.maxHeight }} className="z-[150] overflow-y-auto rounded-[14px] border border-white/10 bg-[#302d2c]/[.99] text-white shadow-[0_18px_42px_rgba(0,0,0,.42)]" onClick={event => event.stopPropagation()}>
    <div className="space-y-1 p-4 pb-3"><div className="mb-2 flex items-center gap-3 px-1 text-[13px] font-bold uppercase tracking-[.06em] text-white/42"><CalendarIcon className="size-4 text-white/48" />Date</div><button type="button" onClick={() => choose(now())} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold transition hover:bg-white/10"><SunIcon className="size-4 text-white/55" />Today</button><button type="button" onClick={() => choose(tomorrow())} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold transition hover:bg-white/10"><CalendarClockIcon className="size-4 text-white/55" />Tomorrow</button><button type="button" onClick={() => choose(nextSunday())} className="flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold transition hover:bg-white/10"><CalendarDaysIcon className="size-4 text-white/55" />Next Sunday</button></div>
    <div className="border-t border-white/10 px-4 pb-4 pt-4"><div className="mb-3 flex items-center gap-2"><p className="min-w-0 flex-1 truncate px-1 text-[15px] font-semibold text-white/75">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</p><button type="button" aria-label="Previous month" onClick={() => shiftMonth(-1)} className="flex size-8 items-center justify-center rounded-lg text-white/40 transition hover:bg-white/10 hover:text-white"><ChevronLeftIcon className="size-4" /></button><button type="button" aria-label="Current month" onClick={() => setMonth(monthStart())} className="flex size-8 items-center justify-center rounded-lg text-white/40 transition hover:bg-white/10 hover:text-white"><SunIcon className="size-4" /></button><button type="button" aria-label="Next month" onClick={() => shiftMonth(1)} className="flex size-8 items-center justify-center rounded-lg text-white/40 transition hover:bg-white/10 hover:text-white"><ChevronRightIcon className="size-4" /></button></div><div className="grid grid-cols-7 gap-y-1 text-center">{weekdays.map((day, index) => <div key={`${day}-${index}`} className="h-7 text-[11px] font-bold leading-7 text-white/35">{day}</div>)}{days.map(day => { const key = dateKey(day); const inMonth = day.getMonth() === month.getMonth(); const isToday = key === today; const isSelected = key === selected; return <button key={key} type="button" aria-label={`Choose ${day.toLocaleDateString()}`} onClick={() => setDay(day)} className={`mx-auto flex size-8 items-center justify-center rounded-lg text-[14px] font-semibold tabular-nums transition hover:bg-white/10 hover:text-white ${inMonth ? 'text-white/60' : 'text-white/20'} ${isToday ? 'text-white/75' : ''} ${isSelected ? 'bg-white/14 text-white' : ''}`}>{isToday ? <SunIcon className="size-4" /> : day.getDate()}</button> })}</div></div>
    <button type="button" onClick={() => choose(undefined)} className="flex h-12 w-full items-center gap-3 border-t border-white/10 px-4 text-left text-[14px] font-semibold text-white transition hover:bg-white/10"><InboxIcon className="size-4 text-white/55" />Cancel</button>
  </div>, document.body)}</>
}
function TaskMoveHandle({ task, collections, onMove, onDragStart, onDragEnd, icon, size = 'size-5', draggable = true }: { task: Task; collections: TaskCollection[]; onMove(task: Task, target: string): void; onDragStart(task: Task, event: DragEvent<HTMLElement>): void; onDragEnd(): void; icon?: ReactNode; size?: string; draggable?: boolean }) { const anchor = useRef<HTMLButtonElement>(null); const [open, setOpen] = useState(false); return <><button ref={anchor} type="button" draggable={draggable} onClick={event => { event.stopPropagation(); setOpen(value => !value) }} onDragStart={event => draggable && onDragStart(task, event)} onDragEnd={onDragEnd} aria-label={`Move ${task.title}`} className={`flex ${size} shrink-0 items-center justify-center rounded-lg text-white/45 transition hover:bg-white/10 hover:text-white/75 ${draggable ? 'cursor-grab active:cursor-grabbing' : ''}`}>{icon ?? <GripVerticalIcon className="size-3.5" />}</button>{open && <TaskMoveMenu anchor={anchor} collections={collections} onClose={() => setOpen(false)} onMove={target => onMove(task, target)} />}</> }
function TaskMoveMenu({ anchor, collections, onClose, onMove }: { anchor: RefObject<HTMLButtonElement | null>; collections: TaskCollection[]; onClose(): void; onMove(target: string): void }) { const [position, setPosition] = useState({ top: 12, left: 12 }); useEffect(() => { const place = () => { const rect = anchor.current?.getBoundingClientRect(); if (!rect) return; setPosition({ top: Math.max(12, Math.min(rect.bottom + 8, window.innerHeight - 66)), left: Math.max(12, Math.min(rect.right - 488, window.innerWidth - 500)) }) }; place(); window.addEventListener('resize', place); return () => window.removeEventListener('resize', place) }, [anchor]); return createPortal(<label style={{ position: 'fixed', top: position.top, left: position.left, width: 'min(488px, calc(100vw - 24px))' }} className="z-[110] flex h-[56px] items-center rounded-[24px] border border-white/10 bg-[#302e2d]/[.99] px-10 text-[20px] font-semibold text-white/75 shadow-[0_16px_40px_rgba(0,0,0,.34)]"><span>Move to</span><select autoFocus defaultValue="" aria-label="Choose a task list" onChange={event => { if (!event.target.value) return; onMove(event.target.value); onClose() }} onBlur={onClose} className="ml-auto max-w-[260px] bg-transparent text-right text-[20px] font-semibold text-white/80 outline-none [color-scheme:dark]"><option value="" disabled className="bg-[#302e2d]">Choose</option><option value="today" className="bg-[#302e2d]">Today</option><option value="upcoming" className="bg-[#302e2d]">Upcoming</option><option value="inbox" className="bg-[#302e2d]">Inbox</option><option value="completed" className="bg-[#302e2d]">Completed</option>{collections.map(list => <option key={list.id} value={list.id} className="bg-[#302e2d]">{list.name}</option>)}</select></label>, document.body) }
function TaskMenuButton({ compact, task, ...props }: RowsProps & { compact: boolean; task: Task }) { const anchor = useRef<HTMLButtonElement>(null); return <><button ref={anchor} type="button" onClick={event => { event.stopPropagation(); props.onMenu(props.menuId === task.id ? null : task.id) }} className={`flex shrink-0 items-center justify-center rounded-full text-white/70 hover:bg-white/10 ${compact ? 'size-8' : 'size-12 bg-white/[.10] hover:bg-white/[.16]'}`} aria-label={`Task actions for ${task.title}`}><MoreHorizontalIcon className={compact ? 'size-5' : 'size-6'} /></button>{props.menuId === task.id && <TaskActionMenu compact={compact} anchor={anchor} task={task} dailyGoal={props.dailyGoalTaskIds.includes(task.id)} onClose={() => props.onMenu(null)} onEdit={() => props.onEditStart(task)} onDate={reminderAt => props.onUpdate(task.id, { reminderAt })} onSubtask={() => props.onSubtaskStart(task.id)} onFocus={() => props.onStartFocus(task)} onDailyGoal={() => props.onSetDailyGoal(task)} onDuplicate={() => props.onDuplicate(task)} onDelete={() => props.onDelete(task.id)} />}</> }
function TaskActionMenu({ compact, anchor, task, dailyGoal, onClose, onEdit, onDate, onSubtask, onFocus, onDailyGoal, onDuplicate, onDelete }: { compact: boolean; anchor: RefObject<HTMLButtonElement | null>; task: Task; dailyGoal: boolean; onClose(): void; onEdit(): void; onDate(value?: string): void; onSubtask(): void; onFocus(): void; onDailyGoal(): void; onDuplicate(): void; onDelete(): void }) {
  const menuRef = useRef<HTMLDivElement>(null)
  const [position, setPosition] = useState({ top: 12, left: 12, maxHeight: 600 })
  const width = 276
  useEffect(() => {
    const place = () => {
      const rect = anchor.current?.getBoundingClientRect()
      if (!rect) return
      const height = Math.min(menuRef.current?.offsetHeight ?? 360, window.innerHeight - 24)
      const maxHeight = compact ? window.innerHeight - 24 : Math.max(160, Math.min(window.innerHeight - 24, window.innerHeight - rect.bottom - 16))
      const top = compact
        ? Math.max(12, rect.top - height - 4)
        : rect.bottom + 4
      setPosition({ top, left: Math.max(12, Math.min(rect.right - width, window.innerWidth - width - 12)), maxHeight })
    }
    place()
    const frame = requestAnimationFrame(place)
    window.addEventListener('resize', place)
    return () => { cancelAnimationFrame(frame); window.removeEventListener('resize', place) }
  }, [anchor, compact])
  const action = (run: () => void) => { run(); onClose() }
  return createPortal(
    <div ref={menuRef} style={{ position: 'fixed', top: position.top, left: position.left, width: `min(${width}px, calc(100vw - 24px))`, maxHeight: position.maxHeight, fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", ui-sans-serif, system-ui, sans-serif', fontSize: '12.32px', lineHeight: 1.2, WebkitFontSmoothing: 'antialiased', '--task-font-scale': '.88' } as React.CSSProperties} className="z-[120] overflow-y-auto rounded-2xl border border-white/10 bg-[#302d2c]/[.99] p-2 text-white shadow-[0_18px_42px_rgba(0,0,0,.38)] backdrop-blur-xl">
      <button type="button" onClick={() => action(onEdit)} className="flex h-10 w-full items-center gap-3 rounded-xl bg-white/[.13] px-3 text-left text-[13px] font-semibold transition hover:bg-white/[.18]"><PencilIcon className="size-4 shrink-0 text-white/65" />Edit <span className="ml-auto text-[11px] text-white/35">⌘E</span></button>
      <div className="flex h-10 items-center gap-1 rounded-xl px-3 text-[13px] font-semibold"><DatePickerButton label="Choose date" value={task.reminderAt} onDate={onDate}><CalendarIcon className="size-4" /></DatePickerButton><span>Date</span><div className="ml-auto flex items-center gap-0.5 text-white/55"><QuickDateButton label="Today" onClick={() => action(() => onDate(now()))}><SunIcon className="size-4" /></QuickDateButton><QuickDateButton label="Tomorrow" onClick={() => action(() => onDate(tomorrow()))}><CalendarClockIcon className="size-4" /></QuickDateButton><QuickDateButton label="Next Sunday" onClick={() => action(() => onDate(nextSunday()))}><CalendarDaysIcon className="size-4" /></QuickDateButton><QuickDateButton label="Clear date" onClick={() => action(() => onDate(undefined))}><InboxIcon className="size-4" /></QuickDateButton></div></div>
      <TaskMenuAction icon={<ListPlusIcon />} label="Subtask" onClick={() => action(onSubtask)} />
      <TaskMenuDivider />
      <TaskMenuAction icon={<PlayIcon />} label="Start Focus Mode" onClick={() => action(onFocus)} />
      <TaskMenuAction icon={<FlagIcon />} label={dailyGoal ? 'Daily Goal' : 'Set as Daily Goal'} onClick={() => action(onDailyGoal)} />
      <TaskMenuDivider />
      <TaskMenuAction icon={<CopyIcon />} label="Duplicate" onClick={() => action(onDuplicate)} />
      <TaskMenuAction icon={<TrashIcon />} label="Delete" danger onClick={() => action(onDelete)} />
    </div>,
    document.body,
  )
}
function QuickDateButton({ label, children, onClick }: { label: string; children: ReactNode; onClick(): void }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className="flex size-8 items-center justify-center rounded-lg hover:bg-white/10">{children}</button> }
function TaskMenuDivider() { return <div className="my-1 h-px bg-white/10" /> }
function TaskMenuAction({ icon, label, danger = false, onClick }: { icon: ReactNode; label: string; danger?: boolean; onClick(): void }) { return <button type="button" onClick={onClick} className={`flex h-10 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-semibold transition hover:bg-white/10 ${danger ? 'text-red-100 hover:bg-red-500/15' : ''}`}><span className="flex size-4 shrink-0 items-center justify-center text-white/65 [&>svg]:size-4">{icon}</span>{label}</button> }
function TaskInput({ draft, setDraft, add, compact }: { draft: string; setDraft(value: string): void; add(): void; compact: boolean }) { return <div className={`flex items-center gap-3 border-t border-white/10 ${compact ? 'px-0 pt-2' : 'px-7 py-5'}`}><PlusIcon className={`shrink-0 text-white/45 ${compact ? 'size-5' : 'size-6'}`} /><input value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.repeat && !event.nativeEvent.isComposing) { event.preventDefault(); add() } }} className={`min-w-0 flex-1 bg-transparent font-semibold outline-none placeholder:text-white/42 ${compact ? 'text-[calc(17px*var(--task-font-scale,0.88))] leading-6' : 'text-[calc(16px*var(--task-font-scale,0.88))] leading-6'}`} placeholder="New task" aria-label="New task" />{!compact && <><button type="button" onClick={add} className="luxe-glass-surface h-10 rounded-full px-4 text-[14px] font-semibold">Add</button><button type="button" aria-label="More task input options" className="flex size-9 items-center justify-center rounded-full text-white/60 hover:bg-white/10"><MoreHorizontalIcon className="size-5" /></button></>}</div> }
function CreateListPopover({ anchor, open, collections, tasks, name, onName, onClose, onCreate, onSelect }: { anchor: HTMLButtonElement | null; open: boolean; collections: TaskCollection[]; tasks: Task[]; name: string; onName(value: string): void; onClose(): void; onCreate(): void; onSelect(id: string): void }) {
  const panel = useRef<HTMLDivElement>(null)
  const [position, setPosition] = useState({ top: 12, left: 12 })
  useEffect(() => {
    if (!open || !anchor) return
    const place = () => {
      const rect = anchor.getBoundingClientRect()
      const width = Math.min(292, window.innerWidth - 24)
      setPosition({
        top: Math.max(12, Math.min(rect.top, window.innerHeight - 360)),
        left: Math.max(12, Math.min(rect.right + 12, window.innerWidth - width - 12)),
      })
    }
    const outside = (event: PointerEvent) => {
      if (!panel.current?.contains(event.target as Node) && !anchor.contains(event.target as Node)) onClose()
    }
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }
    place()
    window.addEventListener('resize', place)
    document.addEventListener('pointerdown', outside)
    document.addEventListener('keydown', escape)
    return () => {
      window.removeEventListener('resize', place)
      document.removeEventListener('pointerdown', outside)
      document.removeEventListener('keydown', escape)
    }
  }, [open, anchor, onClose])
  if (!open || !anchor) return null
  return createPortal(<div ref={panel} style={{ position: 'fixed', top: position.top, left: position.left, width: 'min(292px, calc(100vw - 24px))' }} className="z-[140] rounded-[14px] border border-white/10 bg-[#302d2c]/[.98] p-3 text-white shadow-[0_18px_42px_rgba(0,0,0,.36)]">
    <form onSubmit={event => { event.preventDefault(); onCreate() }} className="space-y-3">
      <div className="flex items-center gap-3 px-1 text-[calc(15px*var(--task-font-scale,0.88))] font-bold"><ListPlusIcon className="size-4 text-white/55" />Create list</div>
      <input autoFocus value={name} onChange={event => onName(event.target.value)} placeholder="List name" className="h-10 w-full rounded-xl border border-white/10 bg-white/[.07] px-3 text-[calc(15px*var(--task-font-scale,0.88))] font-semibold text-white outline-none placeholder:text-white/35 focus:border-white/28 focus:bg-white/[.09]" />
      <button type="submit" disabled={!name.trim()} className="h-10 w-full rounded-xl bg-white/20 px-3 text-[calc(14px*var(--task-font-scale,0.88))] font-bold text-white transition enabled:hover:bg-white/30 disabled:text-white/35">Create list</button>
    </form>
    {collections.length > 0 && <div className="mt-3 border-t border-white/10 pt-2">
      <p className="px-1 pb-1 text-[calc(11px*var(--task-font-scale,0.88))] font-bold uppercase tracking-[.14em] text-white/36">Lists</p>
      {collections.map(list => <button key={list.id} type="button" onClick={() => onSelect(list.id)} className="flex h-9 w-full items-center gap-2 rounded-lg px-2 text-left text-[calc(14px*var(--task-font-scale,0.88))] font-semibold text-white/72 transition hover:bg-white/10 hover:text-white"><ListPlusIcon className="size-4 shrink-0 text-white/42" /><span className="min-w-0 flex-1 truncate">{list.name}</span><span className="text-[calc(12px*var(--task-font-scale,0.88))] tabular-nums text-white/32">{tasks.filter(task => task.listId === list.id && !task.done).length}</span></button>)}
    </div>}
  </div>, document.body)
}
